"""Migracion anotacion 4

Revision ID: 1885657e513c
Revises: 6150ddc14fe0
Create Date: 2019-11-07 19:09:41.879101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1885657e513c'
down_revision = '6150ddc14fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anotacion', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anotacion', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anotacion', type_='foreignkey')
    op.drop_column('anotacion', 'usuario_id')
    # ### end Alembic commands ###
