"""Migracion anotacion 6

Revision ID: 7439a79fe9ba
Revises: efbc6ed030d7
Create Date: 2019-11-08 09:21:25.397319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7439a79fe9ba'
down_revision = 'efbc6ed030d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tratamiento_ibfk_1', 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'color_primario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('color_primario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tratamiento_ibfk_1', 'tratamiento', 'color', ['color_primario'], ['id'])
    # ### end Alembic commands ###
