"""columna ejecuta en anotacion

Revision ID: 77344bdff930
Revises: 335c66500caa
Create Date: 2020-12-27 18:45:26.248557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77344bdff930'
down_revision = '335c66500caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='anotacion', column_name='permite', new_column_name='ejecuta', nullable=False,
                    existing_type=sa.Boolean, )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anotacion', 'ejecuta', new_column_name='permite', existing_type=sa.Boolean)
    # ### end Alembic commands ###
