"""Migracion anotacion 8

Revision ID: 835dd6107d4f
Revises: 9bb61e9e6f2d
Create Date: 2019-11-08 12:15:47.594599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835dd6107d4f'
down_revision = '9bb61e9e6f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('color', sa.Integer(), nullable=True))
    op.drop_constraint('tratamiento_ibfk_1', 'tratamiento', type_='foreignkey')
    op.create_foreign_key(None, 'tratamiento', 'color', ['color'], ['id'])
    op.drop_column('tratamiento', 'color_primario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('color_primario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tratamiento', type_='foreignkey')
    op.create_foreign_key('tratamiento_ibfk_1', 'tratamiento', 'color', ['color_primario'], ['id'])
    op.drop_column('tratamiento', 'color')
    # ### end Alembic commands ###
