"""politica_usuario cambiada

Revision ID: 8bfc83d8f8ee
Revises: e7bb7b11ac7f
Create Date: 2020-02-06 20:01:46.850714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bfc83d8f8ee'
down_revision = 'e7bb7b11ac7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'disponible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('politica_usuario', 'finalizado',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_column('politica_usuario', 'anotar')
    op.drop_column('politica_usuario', 'consolidar')
    op.alter_column('usuario', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('usuario', 'entrenamiento',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'entrenamiento',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('usuario', 'activo',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('politica_usuario', sa.Column('consolidar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('politica_usuario', sa.Column('anotar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('politica_usuario', 'finalizado',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('color', 'disponible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
