"""Migracion anotacion 7

Revision ID: 9bb61e9e6f2d
Revises: 7439a79fe9ba
Create Date: 2019-11-08 09:22:40.398823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb61e9e6f2d'
down_revision = '7439a79fe9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('color_primario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tratamiento', 'color', ['color_primario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'color_primario')
    # ### end Alembic commands ###
