"""asignacion_consolidacion

Revision ID: b5290026ed26
Revises: c8981bfc7b82
Create Date: 2020-01-27 10:14:33.041857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5290026ed26'
down_revision = 'c8981bfc7b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'disponible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.add_column('politica', sa.Column('fecha', sa.Date(), nullable=False))
    op.drop_column('politica', 'finalizada')
    op.add_column('politica_usuario', sa.Column('anotar', sa.Boolean(), nullable=False))
    op.add_column('politica_usuario', sa.Column('consolidar', sa.Boolean(), nullable=False))
    op.alter_column('politica_usuario', 'finalizado',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('usuario', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('usuario', 'entrenamiento',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'entrenamiento',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('usuario', 'activo',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('politica_usuario', 'finalizado',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('politica_usuario', 'consolidar')
    op.drop_column('politica_usuario', 'anotar')
    op.add_column('politica', sa.Column('finalizada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('politica', 'fecha')
    op.alter_column('color', 'disponible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
