"""Migracion anotacion 5

Revision ID: efbc6ed030d7
Revises: 1885657e513c
Create Date: 2019-11-07 19:21:56.027437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbc6ed030d7'
down_revision = '1885657e513c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politica_usuario',
    sa.Column('politica_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['politica_id'], ['politica.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politica_usuario')
    # ### end Alembic commands ###
